### ISSUE TITLE
Problems with token file

### ISSUE THREAD

**Issue by AlexUg** [andr1an/nic-api#4]
While doing authorization by:
```python
api.authorize(username='Your_account/NIC-D',
              password='Your_password',
              token_filename='nic_token.json')
```
i sometimes got errors:
- if file doesn't exists: `Token cache file 'nic_token.json' does not exist`
- if file empty: `Can't load token from cache!\nNo JSON object could be decoded`
- if file contents '{"access_token": "", "token_type": "", "expires_in": ""}': `Can't load token from cache!\ninvalid literal for int() with base 10`
- if file contents '{"access_token": "", "token_type": "", "expires_in": "0"}': `Authorization to NIC.RU DNS APP failed.`
- if file contents like '{"access_token": "A6SF-rVi5ZO0RPd17bmJXU2dmgxh9udbI0pOHu69hcwTurMXYkQbiqZxL8ZShcbaOTY3TIZ0gmr1S4x4V2uFs6g1-Nz", "token_type": "Bearer", "expires_in": "14400"}': `nic_api.exceptions.ExpiredToken: Token is expired!`
Can you provide detailed explanation for correct using of 'token_filename' parameter?

**Comment by andr1an** [comment]
The purpose of this argument is to provide a path to OAuth Bearer token cache. If you already used the module <4h ago, than you are able not to pass username, password – just a token loaded from this JSON file. If it does not exist, then module is trying to get a new one by passing username, password and app credentials from `oauth_config` dict to the special endpoint.

I was assuming no one will try to create or modify the cache file by hand, my bad :) I will rework this part of the code to be more predictable and self-explanatory.

**Comment by AlexUg** [comment]
I didn’t want to create or change the file 'nic_token.json' manually. But when I tried example at first time I got error `Token cache file 'nic_token.json' does not exist`. I had created this file and at next run I got error `Can't load token from cache!\nNo JSON object could be decoded` and so on...
After some manipulation with this file (I can't remember) the example started working. 
At this moment I can say the following -- if you are using Python v3 you can get the example to work, but if you are using Python v2 example does not work. Only after creating the file 'nic_token.json' with v3 the example starts working with v2.

**Comment by AlexUg** [comment]
I apologize. I misinterpreted the error my script was throwing. There is actually no bug.
