### ISSUE TITLE
Repackage with 3.8 support

### ISSUE THREAD

**Issue by residentsummer** [andr1an/nic-api#8]
Hi, @andr1an . Thanks for sharing your work!

I've tried to install the package via `pip` on python 3.8, but it refused to do so due to `python_requires='>=2.7, <3.8'`. Installed manually (cloned and ran `setup.py`) and checked basic functions (getting lists of services, zones, records; adding and deleting A records) - everything worked fine. I guess it's safe to advance the restriction to `>=2.7, <3.9`.

**Comment by andr1an** [comment]
Hi! I can fix this by myself, or also I'll be glad to accept your PR, if you want to contribute. For this particular change, you need to adjust `python_requires` and `classifiers` in `setup.py`, and also add 3.8 test for Travis CI (see `.travis.yml`).

**Comment by residentsummer** [comment]
Actually I've started with a PR, but instead decided to ask you first, just not to forget something. And `.travis.yml` was that thing :)

**Comment by residentsummer** [comment]
I've also bumped package version. Here is the PR: #10

**Comment by andr1an** [comment]
Thanks! That's fine, I merged it.
